version: '3.8'

services:
  backend:
    image: tobiadefami/six-degrees-of-torvalds-backend:v1.02
    build: ./sixdegrees
    volumes:
      - ./sixdegrees:/app/sixdegrees
    environment:
      - GITHUB_APP_CLIENT_ID=${GITHUB_APP_CLIENT_ID}
      - GITHUB_APP_CLIENT_SECRET=${GITHUB_APP_CLIENT_SECRET}
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - SECRET_KEY=${SECRET_KEY}
      - NGINX_HOST=${NGINX_HOST}
    network_mode: host

  frontend:
    image: tobiadefami/six-degrees-of-torvalds-frontend:v1.02
    build: ./REACT/sixdegrees
    # volumes:
    #   - ./REACT/sixdegrees:/app

    command: npm start
    network_mode: host

  nginx:
    image: tobiadefami/six-degrees-of-torvalds-nginx:v1.02
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro

    depends_on:
      - backend
      - frontend
    
    network_mode: host


